version: "1.1"
name: Sum
env:
  baseUrl: http://localhost:8080
tests:
  sum:
    steps:
      - name: sum
        http:
          url: ${{env.baseUrl}}/api/sum
          method: GET
          params: 
            input1: 1
            input2: 2
          check:
            status: 200
            josnpath:
              $.sum: 3