name: frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/**'

defaults:
  run:
    working-directory: frontend

permissions:
  id-token: write
  contents: read 

jobs:
  deploy:
    #test
    runs-on: ubuntu-latest
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.BACKEND_SERVER_IAM_ROLE }}
          aws-region: ap-northeast-1
      - uses: actions/checkout@v3
      - run: aws s3 sync . s3://webhosing-weitang --exact-timestamps --region ap-northeast-1


